# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.9.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QSizePolicy,
    QStatusBar, QTableWidgetItem, QTextEdit, QToolBar,
    QVBoxLayout, QWidget)

from .CalcButton import CalcButton
from .CalcTableWidget import CalcTableWidget
import resource_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(635, 588)
        icon = QIcon()
        icon.addFile(u":/ViCalc/icons/ViCalc.ico", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.action_About = QAction(MainWindow)
        self.action_About.setObjectName(u"action_About")
        self.action_DEG = QAction(MainWindow)
        self.action_DEG.setObjectName(u"action_DEG")
        self.action_DEG.setCheckable(True)
        self.action_RAD = QAction(MainWindow)
        self.action_RAD.setObjectName(u"action_RAD")
        self.action_RAD.setCheckable(True)
        self.action_GRA = QAction(MainWindow)
        self.action_GRA.setObjectName(u"action_GRA")
        self.action_GRA.setCheckable(True)
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionExit.setMenuRole(QAction.MenuRole.NoRole)
        self.actionToggle_Protocol = QAction(MainWindow)
        self.actionToggle_Protocol.setObjectName(u"actionToggle_Protocol")
        self.actionToggle_Protocol.setMenuRole(QAction.MenuRole.NoRole)
        self.action_delete_full_protocol = QAction(MainWindow)
        self.action_delete_full_protocol.setObjectName(u"action_delete_full_protocol")
        self.action_delete_full_protocol.setMenuRole(QAction.MenuRole.NoRole)
        self.action_Help = QAction(MainWindow)
        self.action_Help.setObjectName(u"action_Help")
        self.action_convert_from_hexadecimal = QAction(MainWindow)
        self.action_convert_from_hexadecimal.setObjectName(u"action_convert_from_hexadecimal")
        self.action_convert_from_hexadecimal.setMenuRole(QAction.MenuRole.NoRole)
        self.action_convert_from_binary = QAction(MainWindow)
        self.action_convert_from_binary.setObjectName(u"action_convert_from_binary")
        self.action_convert_from_binary.setMenuRole(QAction.MenuRole.NoRole)
        self.action_convert_from_octal = QAction(MainWindow)
        self.action_convert_from_octal.setObjectName(u"action_convert_from_octal")
        self.action_convert_from_octal.setMenuRole(QAction.MenuRole.NoRole)
        self.action_convert_from_decimal = QAction(MainWindow)
        self.action_convert_from_decimal.setObjectName(u"action_convert_from_decimal")
        self.action_convert_from_decimal.setMenuRole(QAction.MenuRole.NoRole)
        self.action_numeric_format = QAction(MainWindow)
        self.action_numeric_format.setObjectName(u"action_numeric_format")
        self.action_numeric_format.setMenuRole(QAction.MenuRole.NoRole)
        self.actionInsertDateTime = QAction(MainWindow)
        self.actionInsertDateTime.setObjectName(u"actionInsertDateTime")
        self.actionInsertDateTime.setMenuRole(QAction.MenuRole.NoRole)
        self.action_dms_to_dd = QAction(MainWindow)
        self.action_dms_to_dd.setObjectName(u"action_dms_to_dd")
        self.action_dms_to_dd.setMenuRole(QAction.MenuRole.NoRole)
        self.action_sinh = QAction(MainWindow)
        self.action_sinh.setObjectName(u"action_sinh")
        self.action_cosh = QAction(MainWindow)
        self.action_cosh.setObjectName(u"action_cosh")
        self.action_cosh.setMenuRole(QAction.MenuRole.NoRole)
        self.action_tanh = QAction(MainWindow)
        self.action_tanh.setObjectName(u"action_tanh")
        self.action_tanh.setMenuRole(QAction.MenuRole.NoRole)
        self.action_arsinh = QAction(MainWindow)
        self.action_arsinh.setObjectName(u"action_arsinh")
        self.action_arsinh.setMenuRole(QAction.MenuRole.NoRole)
        self.action_arcosh = QAction(MainWindow)
        self.action_arcosh.setObjectName(u"action_arcosh")
        self.action_arcosh.setMenuRole(QAction.MenuRole.NoRole)
        self.action_artanh = QAction(MainWindow)
        self.action_artanh.setObjectName(u"action_artanh")
        self.action_artanh.setMenuRole(QAction.MenuRole.NoRole)
        self.action_rectangular_to_polar = QAction(MainWindow)
        self.action_rectangular_to_polar.setObjectName(u"action_rectangular_to_polar")
        self.action_rectangular_to_polar.setMenuRole(QAction.MenuRole.NoRole)
        self.action_polar_to_rectangular = QAction(MainWindow)
        self.action_polar_to_rectangular.setObjectName(u"action_polar_to_rectangular")
        self.action_polar_to_rectangular.setMenuRole(QAction.MenuRole.NoRole)
        self.action_combination = QAction(MainWindow)
        self.action_combination.setObjectName(u"action_combination")
        self.action_combination.setMenuRole(QAction.MenuRole.NoRole)
        self.action_permutaton = QAction(MainWindow)
        self.action_permutaton.setObjectName(u"action_permutaton")
        self.action_permutaton.setMenuRole(QAction.MenuRole.NoRole)
        self.action_options = QAction(MainWindow)
        self.action_options.setObjectName(u"action_options")
        self.action_options.setMenuRole(QAction.MenuRole.NoRole)
        self.action_square = QAction(MainWindow)
        self.action_square.setObjectName(u"action_square")
        self.action_square.setMenuRole(QAction.MenuRole.NoRole)
        self.action_cube = QAction(MainWindow)
        self.action_cube.setObjectName(u"action_cube")
        self.action_cube.setMenuRole(QAction.MenuRole.NoRole)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.tableWidget = CalcTableWidget(self.centralwidget)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)

        self.verticalLayout.addWidget(self.tableWidget)

        self.expressionLabel = QLabel(self.centralwidget)
        self.expressionLabel.setObjectName(u"expressionLabel")
        self.expressionLabel.setMinimumSize(QSize(0, 18))
        font = QFont()
        font.setPointSize(10)
        self.expressionLabel.setFont(font)

        self.verticalLayout.addWidget(self.expressionLabel)

        self.inputTextEdit = QTextEdit(self.centralwidget)
        self.inputTextEdit.setObjectName(u"inputTextEdit")
        self.inputTextEdit.setMaximumSize(QSize(16777215, 43))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(22)
        font1.setBold(True)
        font1.setKerning(True)
        self.inputTextEdit.setFont(font1)

        self.verticalLayout.addWidget(self.inputTextEdit)

        self.buttonsFrame = QFrame(self.centralwidget)
        self.buttonsFrame.setObjectName(u"buttonsFrame")
        self.buttonsFrame.setMinimumSize(QSize(0, 260))
        self.buttonsFrame.setFrameShape(QFrame.Shape.StyledPanel)
        self.buttonsFrame.setFrameShadow(QFrame.Shadow.Raised)
        self.pushButton0numpad = CalcButton(self.buttonsFrame)
        self.pushButton0numpad.setObjectName(u"pushButton0numpad")
        self.pushButton0numpad.setGeometry(QRect(400, 200, 101, 51))
        self.pushButton0numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton9numpad = CalcButton(self.buttonsFrame)
        self.pushButton9numpad.setObjectName(u"pushButton9numpad")
        self.pushButton9numpad.setGeometry(QRect(500, 50, 51, 51))
        self.pushButton9numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton3numpad = CalcButton(self.buttonsFrame)
        self.pushButton3numpad.setObjectName(u"pushButton3numpad")
        self.pushButton3numpad.setGeometry(QRect(500, 150, 51, 51))
        self.pushButton3numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton2numpad = CalcButton(self.buttonsFrame)
        self.pushButton2numpad.setObjectName(u"pushButton2numpad")
        self.pushButton2numpad.setGeometry(QRect(450, 150, 51, 51))
        self.pushButton2numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonCommaNumpad = CalcButton(self.buttonsFrame)
        self.pushButtonCommaNumpad.setObjectName(u"pushButtonCommaNumpad")
        self.pushButtonCommaNumpad.setGeometry(QRect(500, 200, 51, 51))
        self.pushButtonCommaNumpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonMultiplyNumpad = CalcButton(self.buttonsFrame)
        self.pushButtonMultiplyNumpad.setObjectName(u"pushButtonMultiplyNumpad")
        self.pushButtonMultiplyNumpad.setGeometry(QRect(500, 0, 51, 51))
        self.pushButtonMultiplyNumpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonMinusNumpad = CalcButton(self.buttonsFrame)
        self.pushButtonMinusNumpad.setObjectName(u"pushButtonMinusNumpad")
        self.pushButtonMinusNumpad.setGeometry(QRect(550, 0, 51, 51))
        self.pushButtonMinusNumpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonPlusNumpad = CalcButton(self.buttonsFrame)
        self.pushButtonPlusNumpad.setObjectName(u"pushButtonPlusNumpad")
        self.pushButtonPlusNumpad.setEnabled(True)
        self.pushButtonPlusNumpad.setGeometry(QRect(550, 50, 51, 101))
        self.pushButtonPlusNumpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonDivisionNumpad = CalcButton(self.buttonsFrame)
        self.pushButtonDivisionNumpad.setObjectName(u"pushButtonDivisionNumpad")
        self.pushButtonDivisionNumpad.setGeometry(QRect(450, 0, 51, 51))
        self.pushButtonDivisionNumpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonEnterNumpad = CalcButton(self.buttonsFrame)
        self.pushButtonEnterNumpad.setObjectName(u"pushButtonEnterNumpad")
        self.pushButtonEnterNumpad.setGeometry(QRect(550, 150, 51, 101))
        self.pushButtonEnterNumpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton1numpad = CalcButton(self.buttonsFrame)
        self.pushButton1numpad.setObjectName(u"pushButton1numpad")
        self.pushButton1numpad.setGeometry(QRect(400, 150, 51, 51))
        self.pushButton1numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton8numpad = CalcButton(self.buttonsFrame)
        self.pushButton8numpad.setObjectName(u"pushButton8numpad")
        self.pushButton8numpad.setGeometry(QRect(450, 50, 51, 51))
        self.pushButton8numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton4numpad = CalcButton(self.buttonsFrame)
        self.pushButton4numpad.setObjectName(u"pushButton4numpad")
        self.pushButton4numpad.setGeometry(QRect(400, 100, 51, 51))
        self.pushButton4numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton7numpad = CalcButton(self.buttonsFrame)
        self.pushButton7numpad.setObjectName(u"pushButton7numpad")
        self.pushButton7numpad.setGeometry(QRect(400, 50, 51, 51))
        self.pushButton7numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton5numpad = CalcButton(self.buttonsFrame)
        self.pushButton5numpad.setObjectName(u"pushButton5numpad")
        self.pushButton5numpad.setGeometry(QRect(450, 100, 51, 51))
        self.pushButton5numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton6numpad = CalcButton(self.buttonsFrame)
        self.pushButton6numpad.setObjectName(u"pushButton6numpad")
        self.pushButton6numpad.setGeometry(QRect(500, 100, 51, 51))
        self.pushButton6numpad.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton1 = CalcButton(self.buttonsFrame)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setGeometry(QRect(0, 0, 51, 51))
        self.pushButton1.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton2 = CalcButton(self.buttonsFrame)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setGeometry(QRect(50, 0, 51, 51))
        self.pushButton2.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton3 = CalcButton(self.buttonsFrame)
        self.pushButton3.setObjectName(u"pushButton3")
        self.pushButton3.setGeometry(QRect(100, 0, 51, 51))
        self.pushButton3.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton4 = CalcButton(self.buttonsFrame)
        self.pushButton4.setObjectName(u"pushButton4")
        self.pushButton4.setGeometry(QRect(150, 0, 51, 51))
        self.pushButton4.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton5 = CalcButton(self.buttonsFrame)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setGeometry(QRect(200, 0, 51, 51))
        self.pushButton5.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButton6 = CalcButton(self.buttonsFrame)
        self.pushButton6.setObjectName(u"pushButton6")
        self.pushButton6.setGeometry(QRect(250, 0, 51, 51))
        self.pushButton6.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonQ = CalcButton(self.buttonsFrame)
        self.pushButtonQ.setObjectName(u"pushButtonQ")
        self.pushButtonQ.setGeometry(QRect(25, 50, 51, 51))
        self.pushButtonQ.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonW = CalcButton(self.buttonsFrame)
        self.pushButtonW.setObjectName(u"pushButtonW")
        self.pushButtonW.setGeometry(QRect(75, 50, 51, 51))
        self.pushButtonW.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonE = CalcButton(self.buttonsFrame)
        self.pushButtonE.setObjectName(u"pushButtonE")
        self.pushButtonE.setGeometry(QRect(125, 50, 51, 51))
        self.pushButtonE.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonR = CalcButton(self.buttonsFrame)
        self.pushButtonR.setObjectName(u"pushButtonR")
        self.pushButtonR.setGeometry(QRect(175, 50, 51, 51))
        self.pushButtonR.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonT = CalcButton(self.buttonsFrame)
        self.pushButtonT.setObjectName(u"pushButtonT")
        self.pushButtonT.setGeometry(QRect(225, 50, 51, 51))
        self.pushButtonT.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonZ = CalcButton(self.buttonsFrame)
        self.pushButtonZ.setObjectName(u"pushButtonZ")
        self.pushButtonZ.setGeometry(QRect(275, 50, 51, 51))
        self.pushButtonZ.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonA = CalcButton(self.buttonsFrame)
        self.pushButtonA.setObjectName(u"pushButtonA")
        self.pushButtonA.setGeometry(QRect(50, 100, 51, 51))
        self.pushButtonA.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonS = CalcButton(self.buttonsFrame)
        self.pushButtonS.setObjectName(u"pushButtonS")
        self.pushButtonS.setGeometry(QRect(100, 100, 51, 51))
        self.pushButtonS.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonD = CalcButton(self.buttonsFrame)
        self.pushButtonD.setObjectName(u"pushButtonD")
        self.pushButtonD.setGeometry(QRect(150, 100, 51, 51))
        self.pushButtonD.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonF = CalcButton(self.buttonsFrame)
        self.pushButtonF.setObjectName(u"pushButtonF")
        self.pushButtonF.setGeometry(QRect(200, 100, 51, 51))
        self.pushButtonF.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonG = CalcButton(self.buttonsFrame)
        self.pushButtonG.setObjectName(u"pushButtonG")
        self.pushButtonG.setGeometry(QRect(250, 100, 51, 51))
        self.pushButtonG.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonY = CalcButton(self.buttonsFrame)
        self.pushButtonY.setObjectName(u"pushButtonY")
        self.pushButtonY.setGeometry(QRect(75, 150, 51, 51))
        self.pushButtonY.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonLess = CalcButton(self.buttonsFrame)
        self.pushButtonLess.setObjectName(u"pushButtonLess")
        self.pushButtonLess.setGeometry(QRect(25, 150, 51, 51))
        self.pushButtonLess.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonX = CalcButton(self.buttonsFrame)
        self.pushButtonX.setObjectName(u"pushButtonX")
        self.pushButtonX.setGeometry(QRect(125, 150, 51, 51))
        self.pushButtonX.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonC = CalcButton(self.buttonsFrame)
        self.pushButtonC.setObjectName(u"pushButtonC")
        self.pushButtonC.setGeometry(QRect(175, 150, 51, 51))
        self.pushButtonC.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonV = CalcButton(self.buttonsFrame)
        self.pushButtonV.setObjectName(u"pushButtonV")
        self.pushButtonV.setGeometry(QRect(225, 150, 51, 51))
        self.pushButtonV.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonB = CalcButton(self.buttonsFrame)
        self.pushButtonB.setObjectName(u"pushButtonB")
        self.pushButtonB.setGeometry(QRect(275, 150, 51, 51))
        self.pushButtonB.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonSpace = CalcButton(self.buttonsFrame)
        self.pushButtonSpace.setObjectName(u"pushButtonSpace")
        self.pushButtonSpace.setGeometry(QRect(25, 200, 301, 51))
        self.pushButtonSpace.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonBackspace = CalcButton(self.buttonsFrame)
        self.pushButtonBackspace.setObjectName(u"pushButtonBackspace")
        self.pushButtonBackspace.setGeometry(QRect(300, 0, 51, 51))
        self.pushButtonBackspace.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonEnter = CalcButton(self.buttonsFrame)
        self.pushButtonEnter.setObjectName(u"pushButtonEnter")
        self.pushButtonEnter.setGeometry(QRect(300, 100, 101, 51))
        self.pushButtonEnter.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self.pushButtonAC = CalcButton(self.buttonsFrame)
        self.pushButtonAC.setObjectName(u"pushButtonAC")
        self.pushButtonAC.setGeometry(QRect(400, 0, 51, 51))
        self.pushButtonAC.setFocusPolicy(Qt.FocusPolicy.NoFocus)

        self.verticalLayout.addWidget(self.buttonsFrame)


        self.verticalLayout_2.addLayout(self.verticalLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 635, 22))
        self.menu_File = QMenu(self.menubar)
        self.menu_File.setObjectName(u"menu_File")
        self.menu_Help = QMenu(self.menubar)
        self.menu_Help.setObjectName(u"menu_Help")
        self.menuMode = QMenu(self.menubar)
        self.menuMode.setObjectName(u"menuMode")
        self.menu_Log = QMenu(self.menubar)
        self.menu_Log.setObjectName(u"menu_Log")
        self.menu_Convert = QMenu(self.menubar)
        self.menu_Convert.setObjectName(u"menu_Convert")
        self.menu_Math = QMenu(self.menubar)
        self.menu_Math.setObjectName(u"menu_Math")
        self.menu_Tools = QMenu(self.menubar)
        self.menu_Tools.setObjectName(u"menu_Tools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        font2 = QFont()
        font2.setPointSize(11)
        self.statusbar.setFont(font2)
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.ToolBarArea.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Math.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menu_Convert.menuAction())
        self.menubar.addAction(self.menu_Log.menuAction())
        self.menubar.addAction(self.menu_Tools.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.menu_File.addAction(self.actionExit)
        self.menu_Help.addAction(self.action_Help)
        self.menu_Help.addSeparator()
        self.menu_Help.addAction(self.action_About)
        self.menuMode.addAction(self.action_DEG)
        self.menuMode.addAction(self.action_RAD)
        self.menuMode.addAction(self.action_GRA)
        self.menuMode.addSeparator()
        self.menuMode.addAction(self.action_numeric_format)
        self.menu_Log.addAction(self.actionInsertDateTime)
        self.menu_Log.addAction(self.actionToggle_Protocol)
        self.menu_Log.addSeparator()
        self.menu_Log.addAction(self.action_delete_full_protocol)
        self.menu_Convert.addAction(self.action_convert_from_binary)
        self.menu_Convert.addAction(self.action_convert_from_octal)
        self.menu_Convert.addAction(self.action_convert_from_decimal)
        self.menu_Convert.addAction(self.action_convert_from_hexadecimal)
        self.menu_Convert.addSeparator()
        self.menu_Convert.addAction(self.action_dms_to_dd)
        self.menu_Convert.addSeparator()
        self.menu_Convert.addAction(self.action_rectangular_to_polar)
        self.menu_Convert.addAction(self.action_polar_to_rectangular)
        self.menu_Math.addAction(self.action_square)
        self.menu_Math.addAction(self.action_cube)
        self.menu_Math.addSeparator()
        self.menu_Math.addAction(self.action_sinh)
        self.menu_Math.addAction(self.action_cosh)
        self.menu_Math.addAction(self.action_tanh)
        self.menu_Math.addSeparator()
        self.menu_Math.addAction(self.action_arsinh)
        self.menu_Math.addAction(self.action_arcosh)
        self.menu_Math.addAction(self.action_artanh)
        self.menu_Math.addSeparator()
        self.menu_Math.addAction(self.action_combination)
        self.menu_Math.addAction(self.action_permutaton)
        self.menu_Tools.addAction(self.action_options)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.action_DEG)
        self.toolBar.addAction(self.action_RAD)
        self.toolBar.addAction(self.action_GRA)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"ViCalc", None))
        self.action_About.setText(QCoreApplication.translate("MainWindow", u"&About...", None))
        self.action_DEG.setText(QCoreApplication.translate("MainWindow", u"&DEG", None))
#if QT_CONFIG(shortcut)
        self.action_DEG.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.action_RAD.setText(QCoreApplication.translate("MainWindow", u"&RAD", None))
#if QT_CONFIG(shortcut)
        self.action_RAD.setShortcut(QCoreApplication.translate("MainWindow", u"F3", None))
#endif // QT_CONFIG(shortcut)
        self.action_GRA.setText(QCoreApplication.translate("MainWindow", u"&GRA", None))
#if QT_CONFIG(shortcut)
        self.action_GRA.setShortcut(QCoreApplication.translate("MainWindow", u"F4", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"E&xit", None))
        self.actionToggle_Protocol.setText(QCoreApplication.translate("MainWindow", u"Toggle  &Log / Calculator", None))
#if QT_CONFIG(shortcut)
        self.actionToggle_Protocol.setShortcut(QCoreApplication.translate("MainWindow", u"F5", None))
#endif // QT_CONFIG(shortcut)
        self.action_delete_full_protocol.setText(QCoreApplication.translate("MainWindow", u"&Delete Full Log", None))
        self.action_Help.setText(QCoreApplication.translate("MainWindow", u"&Help", None))
#if QT_CONFIG(shortcut)
        self.action_Help.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.action_convert_from_hexadecimal.setText(QCoreApplication.translate("MainWindow", u"From He&xadecimal...", None))
#if QT_CONFIG(tooltip)
        self.action_convert_from_hexadecimal.setToolTip(QCoreApplication.translate("MainWindow", u"Convert from Hexadecimal", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.action_convert_from_hexadecimal.setShortcut(QCoreApplication.translate("MainWindow", u"F9", None))
#endif // QT_CONFIG(shortcut)
        self.action_convert_from_binary.setText(QCoreApplication.translate("MainWindow", u"From &Binary...", None))
#if QT_CONFIG(shortcut)
        self.action_convert_from_binary.setShortcut(QCoreApplication.translate("MainWindow", u"F6", None))
#endif // QT_CONFIG(shortcut)
        self.action_convert_from_octal.setText(QCoreApplication.translate("MainWindow", u"From &Octal...", None))
#if QT_CONFIG(shortcut)
        self.action_convert_from_octal.setShortcut(QCoreApplication.translate("MainWindow", u"F7", None))
#endif // QT_CONFIG(shortcut)
        self.action_convert_from_decimal.setText(QCoreApplication.translate("MainWindow", u"From &Decimal...", None))
#if QT_CONFIG(shortcut)
        self.action_convert_from_decimal.setShortcut(QCoreApplication.translate("MainWindow", u"F8", None))
#endif // QT_CONFIG(shortcut)
        self.action_numeric_format.setText(QCoreApplication.translate("MainWindow", u"Numeric &Format...", None))
#if QT_CONFIG(shortcut)
        self.action_numeric_format.setShortcut(QCoreApplication.translate("MainWindow", u"F10", None))
#endif // QT_CONFIG(shortcut)
        self.actionInsertDateTime.setText(QCoreApplication.translate("MainWindow", u"Insert &Date and Time", None))
#if QT_CONFIG(shortcut)
        self.actionInsertDateTime.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.action_dms_to_dd.setText(QCoreApplication.translate("MainWindow", u"&DMS to DD...", None))
#if QT_CONFIG(shortcut)
        self.action_dms_to_dd.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+B", None))
#endif // QT_CONFIG(shortcut)
        self.action_sinh.setText(QCoreApplication.translate("MainWindow", u"&sinh", None))
#if QT_CONFIG(shortcut)
        self.action_sinh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_cosh.setText(QCoreApplication.translate("MainWindow", u"&cosh", None))
#if QT_CONFIG(shortcut)
        self.action_cosh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
#endif // QT_CONFIG(shortcut)
        self.action_tanh.setText(QCoreApplication.translate("MainWindow", u"&tanh", None))
#if QT_CONFIG(shortcut)
        self.action_tanh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_arsinh.setText(QCoreApplication.translate("MainWindow", u"&arsinh", None))
#if QT_CONFIG(shortcut)
        self.action_arsinh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.action_arcosh.setText(QCoreApplication.translate("MainWindow", u"a&rcosh", None))
#if QT_CONFIG(shortcut)
        self.action_arcosh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
#endif // QT_CONFIG(shortcut)
        self.action_artanh.setText(QCoreApplication.translate("MainWindow", u"arta&nh", None))
#if QT_CONFIG(shortcut)
        self.action_artanh.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+T", None))
#endif // QT_CONFIG(shortcut)
        self.action_rectangular_to_polar.setText(QCoreApplication.translate("MainWindow", u"&Rectangular to Polar...", None))
        self.action_polar_to_rectangular.setText(QCoreApplication.translate("MainWindow", u"&Polar to Rectangular...", None))
#if QT_CONFIG(shortcut)
        self.action_polar_to_rectangular.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))
#endif // QT_CONFIG(shortcut)
        self.action_combination.setText(QCoreApplication.translate("MainWindow", u"Co&mbination nCr...", None))
#if QT_CONFIG(shortcut)
        self.action_combination.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.action_permutaton.setText(QCoreApplication.translate("MainWindow", u"&Permutaton nPr...", None))
#if QT_CONFIG(shortcut)
        self.action_permutaton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
#endif // QT_CONFIG(shortcut)
        self.action_options.setText(QCoreApplication.translate("MainWindow", u"&Options...", None))
#if QT_CONFIG(shortcut)
        self.action_options.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.action_square.setText(QCoreApplication.translate("MainWindow", u"S&quare", None))
#if QT_CONFIG(shortcut)
        self.action_square.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+2", None))
#endif // QT_CONFIG(shortcut)
        self.action_cube.setText(QCoreApplication.translate("MainWindow", u"C&ube", None))
#if QT_CONFIG(shortcut)
        self.action_cube.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+3", None))
#endif // QT_CONFIG(shortcut)
        self.expressionLabel.setText("")
        self.inputTextEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton0numpad.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.pushButton9numpad.setText(QCoreApplication.translate("MainWindow", u"9", None))
        self.pushButton3numpad.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton2numpad.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pushButtonCommaNumpad.setText(QCoreApplication.translate("MainWindow", u".", None))
        self.pushButtonMultiplyNumpad.setText(QCoreApplication.translate("MainWindow", u"*", None))
        self.pushButtonMinusNumpad.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.pushButtonPlusNumpad.setText(QCoreApplication.translate("MainWindow", u"+", None))
        self.pushButtonDivisionNumpad.setText(QCoreApplication.translate("MainWindow", u"/", None))
        self.pushButtonEnterNumpad.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.pushButton1numpad.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.pushButton8numpad.setText(QCoreApplication.translate("MainWindow", u"8", None))
        self.pushButton4numpad.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton7numpad.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.pushButton5numpad.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton6numpad.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton4.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.pushButton6.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.pushButtonQ.setText(QCoreApplication.translate("MainWindow", u"Q", None))
        self.pushButtonW.setText(QCoreApplication.translate("MainWindow", u"W", None))
        self.pushButtonE.setText(QCoreApplication.translate("MainWindow", u"E", None))
        self.pushButtonR.setText(QCoreApplication.translate("MainWindow", u"R", None))
        self.pushButtonT.setText(QCoreApplication.translate("MainWindow", u"T", None))
        self.pushButtonZ.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.pushButtonA.setText(QCoreApplication.translate("MainWindow", u"A", None))
        self.pushButtonS.setText(QCoreApplication.translate("MainWindow", u"S", None))
        self.pushButtonD.setText(QCoreApplication.translate("MainWindow", u"D", None))
        self.pushButtonF.setText(QCoreApplication.translate("MainWindow", u"F", None))
        self.pushButtonG.setText(QCoreApplication.translate("MainWindow", u"G", None))
        self.pushButtonY.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.pushButtonLess.setText(QCoreApplication.translate("MainWindow", u"<", None))
        self.pushButtonX.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.pushButtonC.setText(QCoreApplication.translate("MainWindow", u"C", None))
        self.pushButtonV.setText(QCoreApplication.translate("MainWindow", u"V", None))
        self.pushButtonB.setText(QCoreApplication.translate("MainWindow", u"B", None))
        self.pushButtonSpace.setText("")
        self.pushButtonBackspace.setText(QCoreApplication.translate("MainWindow", u"<-", None))
        self.pushButtonEnter.setText(QCoreApplication.translate("MainWindow", u"=", None))
        self.pushButtonAC.setText(QCoreApplication.translate("MainWindow", u"AC", None))
        self.menu_File.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menu_Help.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.menuMode.setTitle(QCoreApplication.translate("MainWindow", u"Mo&de", None))
        self.menu_Log.setTitle(QCoreApplication.translate("MainWindow", u"&Log", None))
        self.menu_Convert.setTitle(QCoreApplication.translate("MainWindow", u"&Convert", None))
        self.menu_Math.setTitle(QCoreApplication.translate("MainWindow", u"&Math", None))
        self.menu_Tools.setTitle(QCoreApplication.translate("MainWindow", u"&Tools", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

